[variables]
NIXPACKS_PHP_VERSION = "8.4"

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --ignore-platform-reqs"]

[phases.build]
cmds = [
    "php artisan config:clear",
    "php artisan route:clear",
    "php artisan view:clear"
]

[start]
cmd = "bash docker/entrypoint.sh"
